apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 552.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/invoker-iam-disabled: 'true'
    run.googleapis.com/maxScale: '3'
    run.googleapis.com/minScale: '1'
    run.googleapis.com/operation-id: 9aba012f-7509-4126-b286-22d246c77e46
    run.googleapis.com/urls: '["https://portal-empleabilidad-287614110959.us-central1.run.app","https://portal-empleabilidad-5wye7cqpga-uc.a.run.app"]'
    serving.knative.dev/creator: ti@cftdemagallanes.cl
    serving.knative.dev/lastModifier: dagarcia@cftdemagallanes.cl
  creationTimestamp: '2026-01-23T18:54:50.100997Z'
  generation: 6
  labels:
    cloud.googleapis.com/location: us-central1
    commit-sha: d3b8d937d01d4e52d586dbc1f1fe22bbc3cd2a31
    gcb-build-id: d6193c7d-340d-4463-abca-0c8b97b57edb
    gcb-trigger-id: b01b762b-dd42-4b03-add2-a321458cbc23
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
  name: portal-empleabilidad
  namespace: '287614110959'
  resourceVersion: AAZJEs8jX30
  selfLink: /apis/serving.knative.dev/v1/namespaces/287614110959/services/portal-empleabilidad
  uid: 079fbf55-785e-4941-9dbd-ce0cac44ac55
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 552.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: ngyktpymqu
        commit-sha: d3b8d937d01d4e52d586dbc1f1fe22bbc3cd2a31
        gcb-build-id: d6193c7d-340d-4463-abca-0c8b97b57edb
        gcb-trigger-id: b01b762b-dd42-4b03-add2-a321458cbc23
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: us-central1-docker.pkg.dev/portal-empleabilidad-cft/cloud-run-source-deploy/bolsatrabajocft/portal-empleabilidad:d3b8d937d01d4e52d586dbc1f1fe22bbc3cd2a31
        name: placeholder-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 287614110959-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://portal-empleabilidad-5wye7cqpga-uc.a.run.app
  conditions:
  - lastTransitionTime: '2026-01-23T19:03:02.709090Z'
    message: Provisioning revision instances to receive traffic.
    status: Unknown
    type: Ready
  - lastTransitionTime: '2026-01-23T19:03:13.659515Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2026-01-23T19:03:02.709090Z'
    message: Provisioning revision instances to receive traffic.
    status: Unknown
    type: RoutesReady
  latestCreatedRevisionName: portal-empleabilidad-00005-r6k
  latestReadyRevisionName: portal-empleabilidad-00005-r6k
  observedGeneration: 6
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: portal-empleabilidad-00004-prr
  url: https://portal-empleabilidad-5wye7cqpga-uc.a.run.app
